src/main/java/edu/ucdavis/mw/myinfovault/domain/dossier/Dossier.java
/*
 * Copyright © The Regents of the University of California, Davis campus.
 * All Rights Reserved
 *
 * Unpublished rights reserved under the copyright laws of the United States. The
 * Software contained on this media is proprietary to and embodies the confidential
 * technology of the University of California, Davis.
 * Possession, use, duplication or dissemination of the software and media is
 * authorized only pursuant to a valid written license from University of California, Davis.
 *
 * ---------------------------------------------------------------------------
 * MODULE NAME: Dossier.java
 */

package edu.ucdavis.mw.myinfovault.domain.dossier;

import java.io.File;
import java.io.Serializable;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.TreeMap;

import org.apache.commons.lang.StringUtils;

import edu.ucdavis.mw.myinfovault.domain.action.AcademicAction;
import edu.ucdavis.mw.myinfovault.domain.action.DossierLocation;
import edu.ucdavis.mw.myinfovault.dossier.attributes.DossierAppointmentAttributeKey;
import edu.ucdavis.mw.myinfovault.dossier.attributes.DossierAppointmentAttributes;
import edu.ucdavis.mw.myinfovault.dossier.attributes.DossierAttribute;
import edu.ucdavis.mw.myinfovault.dossier.attributes.DossierAttributeStatus;
import edu.ucdavis.mw.myinfovault.service.person.Appointment;
import edu.ucdavis.mw.myinfovault.service.person.AssignedRole;
import edu.ucdavis.mw.myinfovault.service.person.MivPerson;
import edu.ucdavis.mw.myinfovault.service.person.MivRole;
import edu.ucdavis.mw.myinfovault.service.person.Scope;
import edu.ucdavis.mw.myinfovault.util.MivDocument;
import edu.ucdavis.myinfovault.MIVConfig;
import edu.ucdavis.myinfovault.PropertyManager;
import edu.ucdavis.myinfovault.document.DocumentFormat;
import edu.ucdavis.myinfovault.document.PathConstructor;
import edu.ucdavis.myinfovault.exception.MivSevereApplicationError;

/**
 * This class represents a Dossier in the workflow system. The Dossier object is
 * comprised of data from both the workflow system and MIV database.
 * @author rhendric
 *
 */
public class Dossier implements Serializable
{
    private static final long serialVersionUID = 20090326075502L;


    /**
     * Path constructor for dossier URLs.
     */
    protected static final PathConstructor pathConstructor = new PathConstructor();

    /**
     * {@link MessageFormat} pattern for the dossier URL used in {@link #getDossierPdfUrl(MivRole, int, int)}.
     */
    private static final String DOSSIER_URL = "{0}?roleId={1}&schoolId={2,number,#}&departmentId={3,number,#}";

    /**
     * Filename pattern for a dossier PDF .
     */
    private static final String FILE_PATTERN = "{0}_{1,number,#}_{2,number,#}.{3}";

    private int id;
    private int academicActionID;
    private final long dossierId;
    private MivPerson routingPerson = null;
    private boolean isBaseDataLoaded = false;
    private boolean isAttributeDataLoaded = false;
    private boolean isRecommendedActionFormPresent = false;
    private boolean isAcademicActionFormPresent = false;
    private int primarySchoolId;
    private int primaryDepartmentId;
    private Date submittedDate = null;
    private Date lastRoutedDate = null;
    private Date archivedDate = null;
    private Date completedDate = null;
    private AcademicAction action;
    private DossierReviewType reviewType;
    private String location = null;
    private List<String> previousLocations = new ArrayList<String>();
    private String workflowStatus = null;
    private Map<DossierAppointmentAttributeKey, DossierAppointmentAttributes> appointmentAttributes = new LinkedHashMap<>();


    /**
     * Create a new dossier.
     *
     * @param action
     * @param dossierId
     */
    private Dossier(AcademicAction action, long dossierId)
    {
        this.action = action;
        this.dossierId = dossierId;
    }

    /**
     * Constructs a Dossier WorkflowDocument representing a new document in
     * the workflow system. Creation/committing of the new document is accomplished
     * by the dossier service routeDocument/approveDocument methods.
     *
     * @param action
     * @param dossierId
     * @param annotation
     */
    public Dossier(AcademicAction action,
                   long dossierId,
                   String annotation)
    {
        this(action, dossierId);

        initializeAppointmentAttributeMap();
    }

    /**
     * Create dossier from database record.
     *
     * @param id
     * @param academicActionID
     * @param dossierId
     * @param primarySchoolId
     * @param primaryDepartmentId
     * @param submittedDate
     * @param lastRoutedDate
     * @param archivedDate
     * @param completedDate
     * @param action
     * @param reviewType
     * @param isRecommentedActionFormPresent
     * @param isAcademicActionFormPresent
     * @param location
     * @param previousLocations
     * @param workflowStatus
     */
    public Dossier(int id,
                   int academicActionID,
                   long dossierId,
                   int primarySchoolId,
                   int primaryDepartmentId,
                   Date submittedDate,
                   Date lastRoutedDate,
                   Date archivedDate,
                   Date completedDate,
                   AcademicAction action,
                   DossierReviewType reviewType,
                   boolean isRecommentedActionFormPresent,
                   boolean isAcademicActionFormPresent,
                   String location,
                   List<String> previousLocations,
                   String workflowStatus)
    {
        this(action, dossierId);

        this.id = id;
        this.academicActionID = academicActionID;
        this.primarySchoolId = primarySchoolId;
        this.primaryDepartmentId = primaryDepartmentId;
        this.submittedDate = submittedDate;
        this.lastRoutedDate = lastRoutedDate;
        this.archivedDate = archivedDate;
        this.completedDate = completedDate;
        this.reviewType = reviewType;
        this.location = location;
        this.previousLocations = previousLocations;
        this.workflowStatus = workflowStatus;
        this.isRecommendedActionFormPresent = isRecommentedActionFormPresent;
        this.isAcademicActionFormPresent = isAcademicActionFormPresent;
    }

    /**
     * @return dossier record ID
     */
    public int getId()
    {
        return id;
    }

    /**
     * @param id dossier record ID
     */
    public void setId(int id)
    {
        this.id = id;
    }

    /**
     * @return academicAction ID
     */
    public int getAcademicActionID()
    {
        return this.academicActionID;
    }

    /**
     * @return dossier ID for this Dossier
     */
    public long getDossierId()
    {
        return this.dossierId;
    }

    /**
     * Get the a dossier attribute and create it if it doesn't exist.
     *
     * @param appointmentKey attributes appointment key
     * @param name name of attribute to retrieve
     * @return the dossier attribute for the given appointment and type
     */
    public DossierAttribute getDossierAttribute(DossierAppointmentAttributeKey appointmentKey, String name)
    {
        //get the map of all attributes associated with this dossier appointment
        Map<String, DossierAttribute> dossierAttributes = getAttributesByAppointment(appointmentKey).getAttributes();

        //get the attribute to update
        DossierAttribute attribute = dossierAttributes.get(name);

        //if the attribute is null
        if (attribute == null)
        {
            //create an attribute for this appointment
            attribute = new DossierAttribute(appointmentKey,
                                             MIVConfig.getConfig().getMap("attributetypesbyname").get(name),
                                             getDossierLocation(),
                                             getAction().getActionType());

            //add new attribute to the attributes map
            dossierAttributes.put(name,
                                  attribute);
        }

        return attribute;
    }

    /**
     * Get the workflow node location of this dossier.
     * ** NOTE - This call is a performance killer.
     * Only call when you absolutely need to and avoid calls in a loop.
     *
     * @return String location
     */
    public String getLocation()
    {
//        try
//        {
//            String[] nodes = workflowInfo.getCurrentNodeNames(this.getDossierId());
//            StringBuilder nodeStr = new StringBuilder();
//            for (String node : nodes)
//            {
//                nodeStr.append(node).append(" ");
//            }
//            this.location = nodeStr.toString().trim();
//        }
//        catch (WorkflowException wfe)
//        {
//            this.location = "Unknown";
//            log.log(Level.SEVERE, "Unable to determine current workflow location of dossier " + this.getDossierId(), wfe);
//        }
        return this.location;
    }

    /**
     * Static list of all review locations
     */
    private static final EnumSet<DossierLocation> allReviewCommittees = EnumSet.of(
            DossierLocation.FEDERATION,
            DossierLocation.SENATE_OFFICE,
            DossierLocation.SENATEFEDERATION,
            DossierLocation.FEDERATIONAPPEAL,
            DossierLocation.SENATEAPPEAL,
            DossierLocation.FEDERATIONSENATEAPPEAL
        );

    /**
     *  @return the dossier review committees of this dossier
     */
    public String getReviewCommittees()
    {
        StringBuilder locations = new StringBuilder();
        for (String location : this.previousLocations)
        {

src/main/java/edu/ucdavis/mw/myinfovault/domain/packet/PacketRequestActionType.java
/*
 * Copyright © The Regents of the University of California, Davis campus.
 * All Rights Reserved
 *
 * Unpublished rights reserved under the copyright laws of the United States. The
 * Software contained on this media is proprietary to and embodies the confidential
 * technology of the University of California, Davis.
 * Possession, use, duplication or dissemination of the software and media is
 * authorized only pursuant to a valid written license from University of California, Davis.
 *
 * ---------------------------------------------------------------------------
 * MODULE NAME: PacketRequestAction.java
 */

package edu.ucdavis.mw.myinfovault.domain.packet;

/**
 * The various actions that can be taken for a Packet Request
 * @author rhendric
 *
 */
public enum PacketRequestActionType {

    REQUESTED("Requested"),
    SUBMITTED("Submitted"),
    CANCELED("Canceled");

    private String description;

    private PacketRequestActionType (String description)
    {
        this.description = description;
    }

    /**
     * @return description
     */
    final String getDescription()
    {
        return description;
    }

    /* (non-Javadoc)
     * @see java.lang.Enum#toString()
     */
    @Override
    public String toString() {
        return this.getDescription();
    }

}

src/main/java/edu/ucdavis/mw/myinfovault/domain/raf/RankFilter.java
/*
 * Copyright © The Regents of the University of California, Davis campus.
 * All Rights Reserved
 *
 * Unpublished rights reserved under the copyright laws of the United States. The
 * Software contained on this media is proprietary to and embodies the confidential
 * technology of the University of California, Davis.
 * Possession, use, duplication or dissemination of the software and media is
 * authorized only pursuant to a valid written license from University of California, Davis.
 *
 * ---------------------------------------------------------------------------
 * MODULE NAME: DepartmentTypeFilter.java
 */

package edu.ucdavis.mw.myinfovault.domain.raf;

import edu.ucdavis.mw.myinfovault.service.SearchFilterAdapter;

/**
 * Filters for ranks that are blank (contain no data).
 *
 * @author Craig Gilmore
 * @since 4.3
 */
public class RankFilter extends SearchFilterAdapter<Rank>
{
    /*
     * (non-Javadoc)
     * @see edu.ucdavis.mw.myinfovault.service.SearchFilter#include(java.lang.Object)
     */
    @Override
    public boolean include(Rank item)
    {
        return item.isBlank();
    }
}

src/main/java/edu/ucdavis/mw/myinfovault/domain/signature/Signable.java
/*
 * Copyright © The Regents of the University of California, Davis campus.
 * All Rights Reserved
 *
 * Unpublished rights reserved under the copyright laws of the United States. The
 * Software contained on this media is proprietary to and embodies the confidential
 * technology of the University of California, Davis.
 * Possession, use, duplication or dissemination of the software and media is
 * authorized only pursuant to a valid written license from University of California, Davis.
 *
 * ---------------------------------------------------------------------------
 * MODULE NAME: Signable.java
 */

package edu.ucdavis.mw.myinfovault.domain.signature;

import java.io.File;

import edu.ucdavis.mw.myinfovault.domain.dossier.Dossier;
import edu.ucdavis.mw.myinfovault.service.signature.SignatureStatus;
import edu.ucdavis.mw.myinfovault.util.MivDocument;

/**
 * Defines a signable document.
 *
 * @author Craig Gilmore
 * @since 4.6.2
 */
public interface Signable
{
    /**
     * @return type of signable document
     */
    public MivDocument getDocumentType();
    
    /**
     * @return the signable documents signature status.
     */
    public SignatureStatus getSignatureStatus();
    
    /**
     * @return the dossier PDF file representing this signable document
     */
    public File getDossierFile();

    /**
     * @return document record ID
     */
    public int getDocumentId();

    /**
     * @param documentId document record ID
     */
    public void setDocumentId(int documentId);

    /**
     * @return dossier associated with this document
     */
    public Dossier getDossier();

    /**
     * @return school ID associated with this document
     */
    public int getSchoolId();

    /**
     * @return department ID associated with this document
     */
    public int getDepartmentId();
}

src/main/java/edu/ucdavis/mw/myinfovault/web/spring/manageUsers/AddUserAction.java
/*
 * Copyright © The Regents of the University of California, Davis campus.
 * All Rights Reserved
 *
 * Unpublished rights reserved under the copyright laws of the United States. The
 * Software contained on this media is proprietary to and embodies the confidential
 * technology of the University of California, Davis.
 * Possession, use, duplication or dissemination of the software and media is
 * authorized only pursuant to a valid written license from University of California, Davis.
 *
 * ---------------------------------------------------------------------------
 * MODULE NAME: AddUserAction.java
 */

package edu.ucdavis.mw.myinfovault.web.spring.manageUsers;

import java.util.List;

import org.springframework.webflow.execution.Event;
import org.springframework.webflow.execution.RequestContext;

import edu.ucdavis.mw.myinfovault.service.authorization.AuthorizationService;
import edu.ucdavis.mw.myinfovault.service.authorization.Permission;
import edu.ucdavis.mw.myinfovault.service.person.MivPerson;
import edu.ucdavis.mw.myinfovault.service.person.UserService;
import edu.ucdavis.mw.myinfovault.web.spring.commons.MivFormAction;

/**
 * Webflow form action for adding users.
 *
 * @author Craig Gilmore
 * @since MIV 4.8.1
 */
public class AddUserAction extends MivFormAction
{
    /**
     * Create add user form action bean.
     *
     * @param userService Spring-injected user service
     * @param authService Spring-injected authorization service
     */
    public AddUserAction(UserService userService,
                         AuthorizationService authService)
    {
        super(userService, authService);
    }

    /**
     * Checks if user has general permission to add a user.
     *
     * @param context Request context from webflow
     * @return boolean status, success or error
     */
    public Event hasPermission(RequestContext context)
    {
        return authorizationService.hasPermission(getShadowPerson(context),
                                                  Permission.ADD_USER,
                                                  null)
             ? allowed()
             : denied();
    }

    @Override
    public Event initFormAction(RequestContext context)
    {
        return success();
    }

    /*
     * (non-Javadoc)
     * @see org.springframework.webflow.action.FormAction#bind(org.springframework.webflow.execution.RequestContext)
     */
    @Override
    public Event bind(RequestContext context) throws Exception
    {
        Event status = super.bind(context);

        AddUserForm addForm = (AddUserForm) getFormObject(context);

        List<MivPerson> foundPeople = userService.findPersonByEmail(addForm.getSearchText());

        /*
         * No results and multiple results are errors; there should be only one result.
         */
        addForm.setCampusPerson(foundPeople.size() != 1
                           ? null
                           : foundPeople.get(0));

        return status;
    }

    /**
     * Add the bread crumb appropriate for the child flow.
     *
     * @param context Webflow request context
     * @return Webflow event status
     */
    public Event addBreadcrumb(RequestContext context)
    {
        //add manage users bread crumb
        addBreadcrumbs(context, "Add a New User");

        return success();
    }
}

src/main/webapp/WEB-INF/jsp/decisionlist-table.jsp
<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8"%><%--
--%><%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %><%--
--%><%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %><%--
--%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %><%--
--%>

<c:set var="signatures" value="${requestScope[param.signatureListKey]}"/>

<table class="display" id="${param.tableId}">
    <thead>
        <tr>
            <th class="datatable-column-filter" title="MIV User">MIV User</th>
            <th class="datatable-column-filter" title="School/College">School/College</th>
            <th class="datatable-column-filter" title="Department">Department</th>
            <th class="datatable-column-filter" title="Action">Action</th>
            <th class="datatable-column-filter" title="Release Date">Release Date</th>
            <th class="datatable-column-filter" title="Review Committee">Review Committee</th>                                
        </tr>
    </thead>

    <tbody>
        <c:forEach var="signature" items="${signatures}" varStatus="decRow">
            <c:url var='link' value='${context.request.contextPath}'>
                <c:param name='_flowId' value='${flowRequestContext.activeFlow.id}'/>
                <c:param name='_eventId' value='choose'/>
                <c:param name="_flowExecutionKey" value="${flowExecutionKey}"/>
                <c:param name="dossierId" value="${signature.document.dossier.dossierId}"/>
                <c:param name="schoolId" value="${signature.document.schoolId}"/>
                <c:param name="departmentId" value="${signature.document.departmentId}"/>
                <c:param name="attributeName" value="${signature.document.documentType.attributeName}"/>
            </c:url>
            
            <tr class="${(decRow.count)%2==0?'even':'odd'}">
                <td>
                    <a href="<c:out escapeXml='true' value='${link}'/>"
                       title="${signature.document.dossier.candidate.sortName}">${signature.document.dossier.candidate.sortName}</a>
                </td>

                <td>${signature.document.schoolName}</td>
                <td>${signature.document.departmentName}</td>
                <td>${signature.document.dossier.action.description}</td>
                <td><fmt:formatDate type="both" value="${signature.createdDate}" /></td>
                <td>${signature.document.dossier.reviewCommittees}</td>                                        
            </tr>                                                    
        </c:forEach>
    </tbody>
    
    <tfoot>
        <tr>
            <th colspan="6">${fn:length(signatures)} Entries found</th>
        </tr>
    </tfoot>
</table>

src/main/webapp/WEB-INF/jsp/decisionsignature.jsp
<%@ page contentType="text/html; charset=utf-8" pageEncoding="utf-8"%><%--
--%><%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %><%--
--%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %><%--
--%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%><%--
--%><%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %><%--
--%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %><%--
--%><%@ taglib prefix="miv" uri="mivTags" %><%--
--%><%@ taglib prefix="jwr" uri="http://jawr.net/tags" %><%--
--%><c:set var="wetSignatureUrl" value="${form.wetSignatureUrl}"/><%--
--%><spring:message var="pageTitle" text="${strings.pageTitle}" arguments="${form.decision.documentType.alternateDescription}"/><%--
--%><!DOCTYPE HTML>
<html>
<head>
    <title>MIV &ndash; ${pageTitle}</title>

    <%@ include file="/jsp/metatags.html" %>

    <link rel="stylesheet" type="text/css" media="screen" href="<c:url value='/css/mivcommon.css'/>">
    <link rel="stylesheet" type="text/css" media="screen" href="<c:url value='/css/mivEnterData.css'/>">
    <link rel="stylesheet" type="text/css" media="screen" href="<c:url value='/css/miv-forms.css'/>">
    <link rel="stylesheet" type="text/css" media="screen" href="<c:url value='/css/decision.css'/>">
    <link rel="stylesheet" type="text/css" media="print" href="<c:url value='/css/printdecision.css'/>">

    <script type="text/javascript" src="<c:url value='/js/mivcommon.js'/>"></script>
    <jwr:script src="/bundles/mivvalidation.js" />
    <script type="text/javascript" src="<c:url value='/js/decisionsignature.js'/>"></script>
</head>
<body>
    <jsp:include page="/jsp/mivheader.jsp" />

    <jsp:include page="breadcrumbs.jsp">
        <jsp:param value="${pageTitle}" name="pageTitle"/>
    </jsp:include>

    <div id="main">
        <h1>${pageTitle}</h1>

        <jsp:include page="binderrors.jsp" />

        <div id="headingbox" class="formline">
            <div><strong>${strings.candidateLabel}</strong> ${form.decision.dossier.candidate.displayName}</div>
            <div>
                <strong>${strings.viewPdfLabel}</strong>
                <a href="<c:out escapeXml="true" value="${form.dossierUrl}"/>"
                   title="${form.decision.dossier.action.description}">${form.decision.dossier.action.description}</a>
            </div>
            <div>
                <strong>${strings.primaryDeptLabel}</strong>
                ${form.decision.dossier.primaryDepartment.school}${!empty form.decision.dossier.primaryDepartment.description ? ' &ndash; ' : ''}
                ${form.decision.dossier.primaryDepartment.description}
            </div>

            <%-- if not appeal decision --%>
            <c:if test="${form.decision.documentType != 'DEANS_APPEAL_DECISION'
                       && form.decision.documentType != 'VICEPROVOSTS_APPEAL_DECISION'
                       && form.decision.documentType != 'JOINT_DEANS_APPEAL_RECOMMENDATION'}">
                <div><strong>${strings.presentRankLabel}</strong> ${form.decision.present}</div>
                <div><strong>${strings.proposedRankLabel}</strong> ${form.decision.proposed}</div>
            </c:if>
            <div style="margin-top: 0.6em;">
                <strong>${strings.effectiveDateLabel}</strong>
                <fmt:formatDate value="${form.decision.dossier.action.effectiveDate}" pattern="M/d/yyyy" />
            </div>
        </div><!-- #headingbox -->

        <form:form id="signatureForm" cssClass="mivdata" method="post" commandName="form">
            <%-- wet signature upload and print buttons only available to provost/chancellor signable decisions/recommendations --%>
            <c:if test="${form.decision.documentType.allowedSigner == 'PROVOST'
                       || form.decision.documentType.allowedSigner == 'CHANCELLOR'}">
               <div class="formline">
                    <miv:permit roles="SYS_ADMIN|VICE_PROVOST_STAFF|OCP_STAFF" usertype="REAL">
                        <button id="printPdf"
                                title="<spring:message text="${tooltips.printWetSignature}"
                                                       arguments="${form.decision.documentType.description}"/>">${labels.printWetSignature}</button>
                    </miv:permit>

                    <%-- OCP staff may not upload/remove wet signatures --%>
                    <miv:permit roles="!OCP_STAFF">
                        <c:choose>
                            <%-- wet signature uploaded --%>
                            <c:when test="${not empty wetSignatureUrl}">
                                <a href="<c:out escapeXml='true' value='${wetSignatureUrl}'/>"
                                   title="<spring:message text="${tooltips.viewWetSignature}"
                                                          arguments="${form.decision.documentType.description}"
                                                          htmlEscape="false"/>">${form.decision.documentType.description}</a>

                                <button type="submit" formnovalidate
                                        name="_eventId_remove"
                                        title="<spring:message text="${tooltips.removeWetSignature}"
                                                               arguments="${form.decision.documentType.description}"/>">${labels.removeWetSignature}</button>
                            </c:when>

                            <%-- no wet signature uploaded --%>
                            <c:otherwise>
                                <miv:permit roles="SYS_ADMIN|VICE_PROVOST_STAFF" usertype="REAL">
                                    <button type="submit" formnovalidate
                                            name="_eventId_add"
                                            title="<spring:message text="${tooltips.addWetSignature}"
                                                                   arguments="${form.decision.documentType.description}"/>">${labels.addWetSignature}</button>
                                </miv:permit>
                            </c:otherwise>
                        </c:choose>
                    </miv:permit>
                </div>
            </c:if>

            <%-- OCP staff may not sign --%>
            <miv:permit roles="!OCP_STAFF">
                <fieldset class="mivfieldset formline">
                    <legend><spring:message text="${labels.action}"
                                            arguments="${form.decision.dossier.delegationAuthorityDescription}"/></legend>

                    <div>
                        <fieldset class="mivfieldset decision">
                            <legend><spring:message text="${form.decision.documentType.decision ? labels.decision : labels.recommendation}"
                                                    arguments="${form.decision.dossier.delegationAuthorityDescription}"/></legend>

                            <ul>
                                <form:radiobuttons path="decision.decisionType"
                                                   items="${form.decisionTypes}"
                                                   element="li"/>
                            </ul>
                        </fieldset>

                        <c:if test="${not empty form.decisionTypes.OTHER}">
                            <div id="ifother">
                            <spring:message text="${strings.ifOther}" arguments="${form.decision.documentType.allowedSigner.description}"/>
                            </div>
                        </c:if>

                        <div>
                            <form:checkbox path="decision.contraryToCommittee"
                                           label="${labels.contraryToCommittee}"
                                           title="${tooltips.contraryToCommittee}"/>
                        </div>
                    </div>
                </fieldset>

                <div class="formline">
                    <spring:bind path="decision.comments">
                        <div><label for="${status.expression}"><spring:message text="${strings.commentsLabel}"
                                                                               arguments="${form.decision.documentType.allowedSigner.description}"
                                                                               htmlEscape="false"/></label></div>

                        <textarea id="${status.expression}"
                                  name="${status.expression}"
                                  rows="5" cols="80" autofocus>${status.value}</textarea>
                    </spring:bind>
                </div>
                <div id="lineBreakNote">${strings.commentsDagger}</div>

                <p><spring:message text="${strings.agreement}" arguments="${pageTitle}" htmlEscape="false"/></p>

                <div class="buttonset">
                    <input type="submit"
                           title="${pageTitle}"
                           name="_eventId_sign"
                           value="${pageTitle}">
                    <input type="submit"
                           title="${tooltips.cancelButton}"
                           name="_eventId_breadcrumb1"
                           value="${labels.cancelButton}"
                           formnovalidate>
                </div>
            </miv:permit>
        </form:form>
    </div>

    <div id="printpage">
        <div class="decisiontype">${form.decision.documentType.alternateDescription}</div>
        <div class="candidate">${form.decision.dossier.candidate.displayName},&nbsp;${form.decision.dossier.action.delegationAuthority.description}:&nbsp;${form.decision.dossier.action.description}</div>

        <ul class="selections">
        <c:forEach var="decisionType" items="${form.decisionTypes}">
                        <li>${decisionType["value"]}</li>
        </c:forEach>

        </ul>

        <c:if test="${not empty form.decisionTypes.OTHER}">
        <div id="ifotherPrint">
            <spring:message text="${strings.ifOtherPrint}" arguments="${form.decision.documentType.allowedSigner.description}"/>
        </div>
        </c:if>

        <ul class="selections">
                <li>${labels.contraryToCommittee}</li>
        </ul>

        <div class="commentslabel"><spring:message text="${strings.commentsLabel}" arguments="${form.decision.documentType.allowedSigner.description}"/></div>
        <div class="commentsarea">&nbsp;</div>
        <div class="signature">Signed:<span class="signatureline">&nbsp;</span></div>
        <div class="date">Date:<span class="dateline">&nbsp;</span></div>
        <div class="signer">${form.signingPerson.displayName}</div>
    </div>

    <jsp:include page="/jsp/miv_small_footer.jsp" />

</body>
</html><%--
vi: se ts=8 sw=4 et:
--%>